// ── Manual DB types ───────────────────────────────────────────────────────────
//
// Normally generated by: supabase gen types typescript --local
// Written manually here so the project compiles without a live Supabase project.
// Regenerate after running migrations: pnpm supabase gen types typescript --local > src/lib/supabase/database.types.ts
//
// IMPORTANT: GenericTable (from @supabase/supabase-js) requires a Relationships
// field on every table definition. Without it, Supabase's schema resolution
// falls through to `never` and all table queries lose type information.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type PermissionLevel = 'owner' | 'editor' | 'viewer'

type SnapshotTrigger = 'manual' | 'autosave' | 'revision_open' | 'revision_close'
type InviteStatus = 'pending' | 'accepted' | 'declined'
type ResourceType = 'project' | 'script'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          display_name?: string
          avatar_url?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          id: string
          title: string
          description: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          description?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'projects_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      project_members: {
        Row: {
          project_id: string
          user_id: string
          role: PermissionLevel
          invited_by: string | null
          added_at: string
        }
        Insert: {
          project_id: string
          user_id: string
          role?: PermissionLevel
          invited_by?: string | null
          added_at?: string
        }
        Update: {
          role?: PermissionLevel
        }
        Relationships: [
          {
            foreignKeyName: 'project_members_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      scripts: {
        Row: {
          id: string
          project_id: string
          title: string
          blocks: Json
          created_by: string
          created_at: string
          updated_at: string
          current_revision_set_id: string | null
        }
        Insert: {
          id?: string
          project_id: string
          title: string
          blocks?: Json
          created_by: string
          created_at?: string
          updated_at?: string
          current_revision_set_id?: string | null
        }
        Update: {
          title?: string
          blocks?: Json
          updated_at?: string
          current_revision_set_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'scripts_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'scripts_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      script_members: {
        Row: {
          script_id: string
          user_id: string
          role: PermissionLevel
          invited_by: string | null
          added_at: string
        }
        Insert: {
          script_id: string
          user_id: string
          role?: PermissionLevel
          invited_by?: string | null
          added_at?: string
        }
        Update: {
          role?: PermissionLevel
        }
        Relationships: [
          {
            foreignKeyName: 'script_members_script_id_fkey'
            columns: ['script_id']
            isOneToOne: false
            referencedRelation: 'scripts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'script_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      script_snapshots: {
        Row: {
          id: string
          script_id: string
          blocks: Json
          taken_by: string
          taken_at: string
          label: string | null
          trigger_type: SnapshotTrigger
        }
        Insert: {
          id?: string
          script_id: string
          blocks: Json
          taken_by: string
          taken_at?: string
          label?: string | null
          trigger_type?: SnapshotTrigger
        }
        Update: {
          label?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'script_snapshots_script_id_fkey'
            columns: ['script_id']
            isOneToOne: false
            referencedRelation: 'scripts'
            referencedColumns: ['id']
          }
        ]
      }
      revision_sets: {
        Row: {
          id: string
          script_id: string
          name: string
          color: string
          opened_at: string
          closed_at: string | null
          open_snapshot_id: string
          close_snapshot_id: string | null
          created_by: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          script_id: string
          name: string
          color?: string
          opened_at?: string
          closed_at?: string | null
          open_snapshot_id: string
          close_snapshot_id?: string | null
          created_by: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          color?: string
          closed_at?: string | null
          close_snapshot_id?: string | null
          is_active?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'revision_sets_script_id_fkey'
            columns: ['script_id']
            isOneToOne: false
            referencedRelation: 'scripts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'revision_sets_open_snapshot_id_fkey'
            columns: ['open_snapshot_id']
            isOneToOne: false
            referencedRelation: 'script_snapshots'
            referencedColumns: ['id']
          }
        ]
      }
      invites: {
        Row: {
          id: string
          resource_type: ResourceType
          resource_id: string
          invited_user_id: string
          invited_by: string
          role: PermissionLevel
          status: InviteStatus
          created_at: string
        }
        Insert: {
          id?: string
          resource_type: ResourceType
          resource_id: string
          invited_user_id: string
          invited_by: string
          role: PermissionLevel
          status?: InviteStatus
          created_at?: string
        }
        Update: {
          status?: InviteStatus
        }
        Relationships: [
          {
            foreignKeyName: 'invites_invited_user_id_fkey'
            columns: ['invited_user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'invites_invited_by_fkey'
            columns: ['invited_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          action: string
          resource_type: string
          resource_id: string
          metadata: Json | null
          ip_address: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          resource_type: string
          resource_id: string
          metadata?: Json | null
          ip_address?: string | null
          created_at?: string
        }
        Update: Record<string, never>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      is_project_member: {
        Args: { p_project_id: string; p_user_id: string }
        Returns: boolean
      }
      project_role: {
        Args: { p_project_id: string; p_user_id: string }
        Returns: PermissionLevel | null
      }
      effective_script_role: {
        Args: { p_script_id: string; p_user_id: string }
        Returns: PermissionLevel | null
      }
      lookup_user_by_email: {
        Args: { p_email: string }
        Returns: { user_id: string; display_name: string }[]
      }
    }
    Enums: {
      permission_level: PermissionLevel
    }
    CompositeTypes: Record<string, never>
  }
}
