// ── Manual DB types ───────────────────────────────────────────────────────────
//
// Normally generated by: supabase gen types typescript --local
// Written manually here so the project compiles without a live Supabase project.
// Regenerate after running migrations: pnpm supabase gen types typescript --local > src/lib/supabase/database.types.ts
//
// IMPORTANT: GenericTable (from @supabase/supabase-js) requires a Relationships
// field on every table definition. Without it, Supabase's schema resolution
// falls through to `never` and all table queries lose type information.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type PermissionLevel = 'owner' | 'editor' | 'viewer'

type ScriptFormat = 'feature' | 'pilot' | 'spec' | 'short'
type SnapshotTrigger = 'manual' | 'autosave' | 'revision_open' | 'revision_close'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          display_name?: string
          avatar_url?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          id: string
          title: string
          description: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          description?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'projects_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      project_members: {
        Row: {
          project_id: string
          user_id: string
          role: PermissionLevel
          invited_by: string | null
          added_at: string
        }
        Insert: {
          project_id: string
          user_id: string
          role?: PermissionLevel
          invited_by?: string | null
          added_at?: string
        }
        Update: {
          role?: PermissionLevel
        }
        Relationships: [
          {
            foreignKeyName: 'project_members_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      scripts: {
        Row: {
          id: string
          project_id: string
          title: string
          format: ScriptFormat
          blocks: Json
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          title: string
          format?: ScriptFormat
          blocks?: Json
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          format?: ScriptFormat
          blocks?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'scripts_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'scripts_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      script_members: {
        Row: {
          script_id: string
          user_id: string
          role: PermissionLevel
          invited_by: string | null
          added_at: string
        }
        Insert: {
          script_id: string
          user_id: string
          role?: PermissionLevel
          invited_by?: string | null
          added_at?: string
        }
        Update: {
          role?: PermissionLevel
        }
        Relationships: [
          {
            foreignKeyName: 'script_members_script_id_fkey'
            columns: ['script_id']
            isOneToOne: false
            referencedRelation: 'scripts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'script_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      script_snapshots: {
        Row: {
          id: string
          script_id: string
          blocks: Json
          taken_by: string
          taken_at: string
          label: string | null
          trigger_type: SnapshotTrigger
        }
        Insert: {
          id?: string
          script_id: string
          blocks: Json
          taken_by: string
          taken_at?: string
          label?: string | null
          trigger_type?: SnapshotTrigger
        }
        Update: {
          label?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'script_snapshots_script_id_fkey'
            columns: ['script_id']
            isOneToOne: false
            referencedRelation: 'scripts'
            referencedColumns: ['id']
          }
        ]
      }
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          action: string
          resource_type: string
          resource_id: string
          metadata: Json | null
          ip_address: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          resource_type: string
          resource_id: string
          metadata?: Json | null
          ip_address?: string | null
          created_at?: string
        }
        Update: Record<string, never>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      permission_level: PermissionLevel
    }
    CompositeTypes: Record<string, never>
  }
}
